In [1]:
#import pandas
import pandas as pd

In [2]:
data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [5]:
data = [1,2,3,4,5,6]
i = ['A','B','C','D','E','']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
E    5
F    6
dtype: int64


In [6]:
data = {'A':10,'B':20,'C':30,'D':40,'E':50}
series = pd.Series(data)
print(series)

A    10
B    20
C    30
D    40
E    50
dtype: int64


In [7]:
series.replace(20,100)

A     10
B    100
C     30
D     40
E     50
dtype: int64

In [8]:
import numpy as np
data = np.array([100,200,300])
series = pd.Series(data, index=['a','b','c'])
print(series)


a    100
b    200
c    300
dtype: int32


In [9]:
#create pandas dataframe from dictionary of Lists
import pandas as pd
data = {'Name': ['Alice','bob','mary'], 'age': [25,30,34],'country':['usa','uk','aus']}
df = pd.DataFrame(data)
print(df)

    Name  age country
0  Alice   25     usa
1    bob   30      uk
2   mary   34     aus


In [14]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array,columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


AttributeError: module 'numpy' has no attribute 'DataFrame'

In [15]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array)
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


AttributeError: module 'numpy' has no attribute 'DataFrame'

In [16]:
###CREATE A DATAFRAME

In [18]:
Iris_df = pd.read_excel("iris.xlsx")
print(Iris_df)

AttributeError: module 'numpy' has no attribute 'read_excel'